name: CI micro_ros_utilities

on:
  push:
    branches: [ main, galactic ]
  pull_request:
    branches: [ main, galactic ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-20.04, windows-latest, macOS-latest ]
        os: [ ubuntu-20.04 ]
        ros_distribution: [ rolling, galactic ]
        include:
          - docker_image: ubuntu:focal
            ros_distribution: rolling
          - docker_image: ubuntu:focal
            ros_distribution: galactic
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.2.1
      with:
        use-ros2-testing: true
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.2.1
      with:
        package-name: "micro_ros_utilities"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [ "coverage-gcc" ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
