name: CI micro_ros_utilities

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: iron
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@0.6.2
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.3.2
      with:
        package-name: "micro_ros_utilities"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [ "coverage-gcc" ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
