name: CI micro_ros_utilities

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
    container:
      image: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v7

    - uses: ros-tooling/setup-ros@0.7.19
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}

    - uses : ros-tooling/action-ros-ci@0.4.8
      with:
        package-name: "micro_ros_utilities"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        coverage-result: false
