name: CI micro_ros_utilities

on:
  push:
    branches: [ main, galactic, humble ]
  pull_request:
    branches: [ main, galactic, humble ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:focal
            ros_distribution: rolling
          - docker_image: ubuntu:focal
            ros_distribution: galactic
          - docker_image: ubuntu:jammy
            ros_distribution: humble
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.3.2
    - uses : ros-tooling/action-ros-ci@0.2.5
      with:
        package-name: "micro_ros_utilities"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [ "coverage-gcc" ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
